spring:
  application:
    name: FleetHub
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?TimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: update
fleet-hub:
  jwt:
    expiration-seconds: 36000
    secret-key: ${SECRET_KEY}
  security:
    whitelist: "/login,/signup"