spring:
  application:
    name: FleetHub
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?TimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
fleet-hub:
  jwt:
    expiration-seconds: 36000
    secret-key: ${SECRET_KEY}
  security:
    whitelist: "/auth/login,/auth/signup,/auth/login/iam-user"
  iam:
    id: 1
    name: "IAM"
    code: "IAM"
    description: "Identity and Access Management"
  project-management:
    id: 2
    name: "Project Management"
    code: "PROJECT_MANAGEMENT"
    description: "Responsible for managing operational projects that organize and group vehicles, activities, and resources. Projects can represent worksites, contracts, operational areas, or any business entity that requires tracking of assets and operations."
  fleet-management:
    id: 3
    name: "Fleet Management"
    code: "FLEET_MANAGEMENT"
    description: "Module responsible for registering vehicles, machines, and fleet assets. It centralizes and organizes asset information to support other operational processes like fueling and maintenance."